version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install
  - cd example
  - yarn install

build: off

before_test:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

test_script:
  - yarn test
