version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "10"
    - nodejs_version: "8"
  NOW_TOKEN:
    secure: hTCahB+WhZAzqXg2hoKa6BbNrphYvmIc0jcrYZh9vP4=

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install
  - cd example
  - yarn install


build: off

before_test:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))
  - ps: Set-ScreenResolution 1920 1080

test_script:
  - yarn test

on_finish:
  - cd snapshots
  - npx now --public --token %NOW_TOKEN%
