os:
  - linux
  - osx

dist: trusty

language: node_js

node_js:
  - '10'
  - '9'

sudo: required

addons:
  apt:
    packages:
      - libgtk-3-dev
      - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install click   ; fi

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn install
  - cd example && yarn install

script: node index.js
