os:
  - linux
  - osx
dist: trusty
language: node_js
node_js:
  - '11'
  - '10'
  - '8'
sudo: false
addons:
  apt:
    update: true
    packages:
    - libgtk-3-dev
    - xvfb
    - at-spi2-core

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install click pyobjc-framework-Quartz; fi
install:
  - yarn install
  - cd example && yarn install

before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then      Xvfb :99 -ac -screen 0 1920x1080x24 > /dev/null 2>&1 &  fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then sudo Xvfb :99 -ac -screen 0 1280x800x32  & fi
  - sleep 3
script:
  - yarn test
