os:
  - linux
  - osx

dist: trusty

language: node_js

node_js:
  - '10'
  - '9'

sudo: required

addons:
  apt:
    packages:
      - libgtk-3-dev
      - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install click pyobjc-framework-Quartz ; fi

install:
  - yarn install
  - cd example && yarn install

before_script:
  -  export DISPLAY=:99.0
  -  if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sh -e /etc/init.d/xvfb start; fi
  -  if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok ) & fi
  -  sleep 3

script: node index.js
