os:
  - linux
  - osx

dist: trusty

language: node_js

node_js:
  - '10'
  - '9'

sudo: required

addons:
  apt:
    packages:
      - libgtk-3-dev
      - xvfb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install click pyobjc-framework-Quartz ; fi

install:
  - export DISPLAY=':99.0'
  - 
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - yarn install
  - cd example && yarn install

script: node index.js
